steps:

  - id: "decrypting"
    name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - kms 
      - decrypt 
      - --ciphertext-file=./storage/credentials/google/service-account-storage.json.enc
      - --plaintext-file=./storage/credentials/google/service-account-storage.json
      - --location=global
      - --keyring=fullcycle
      - --key=service-account

  - id: "Running docker-compose"
    name: 'docker/compose'
    args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']
    env: 
      - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
      - GOOGLE_CLOUD_KEY_FILE=service-account-storage.json
      - GOOGLE_CLOUD_STORAGE_BUCKET=dalves_code-micro-videos  
      - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/dalves_code-micro-videos
      - TESTING_PROD=true

  - id: "Chown in /var/www"
    name: 'docker'
    args: ['exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www']

  - id: "Running docker ps"
    name: 'docker'
    args: ['ps']

  - id: "Running composer"
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'composer', 'install']

  - id: "Copying .env"
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

  - id: "Copying .env.testing"
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.testing.example', '.env.testing']

  - id: "show .env.testing"
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'cat', '.env.testing']

  - id: "Running key:generete"
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']

  - id: "Running migrations"
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate']

  - id: "Running unit tests"
    name: 'docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', 'vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']


